# Generated by Django 5.0.1 on 2024-01-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buck',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
